import type { Metadata } from "next";
import "./globals.css";
import Framepage from "./Framepage/page";
      
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <Framepage>
          {children}
        </Framepage>
      </body>
    </html>
  );
}
